FROM python:3.14-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:0.9.26 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_CACHE_DIR=/tmp/uv-cache

RUN groupadd -r liogroup && useradd -r -g liogroup -s /sbin/nologin liouser

WORKDIR /app

RUN chown liouser:liogroup /app

USER liouser

COPY --chown=liouser:liogroup pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project

COPY --chown=liouser:liogroup src/ ./src/

CMD ["uv", "run", "python", "-m", "src.main"]
