services:
  postgres_test:
    image: postgres:18.1
    container_name: test_lio_agent_postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - lio_postgres_data_test:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    env_file:
      - ../tests/.env.test
    networks:
      - lio_agent_net

volumes:
  lio_postgres_data_test:
    external: true

networks:
  lio_agent_net:
    external: true
