services:
  lio-agent-python:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: lio-agent-app-python
    restart: always
    volumes:
      - ../src:/app/src
      - /app/.venv
    ports:
      - "5679:5679"
    environment:
      - DEBUG_MODE=false
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PW}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - BOT_TOKEN=${TOKEN_TELEGRAM_LIO}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
      - OLLAMA_URL=${OLLAMA_URL}
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    env_file:
      - ../.env
    networks:
      - lio_agent_net

  postgres:
    image: postgres:18.1
    container_name: lio_agent_postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - lio_postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - lio_agent_net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - lio_ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 10s
      start_period: 20s
      retries: 5
    networks:
      - lio_agent_net
    # GPU NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Contenedor auxiliar para descargar el modelo
  ollama-pull-model:
    image: curlimages/curl:latest
    container_name: ollama-pull-model
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: [ "curl", "-X", "POST", "http://ollama:11434/api/pull", "-d", '{"name": "llama3.1"}' ]
    networks:
      - lio_agent_net

volumes:
  lio_ollama_data:
    external: true

  lio_postgres_data:
    external: true

networks:
  lio_agent_net:
    external: true
