FROM python:3.14-slim-trixie

# Installing uv
COPY --from=ghcr.io/astral-sh/uv:0.9.26 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Copy the configuration files
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-install-project
# Copy the project into the image

COPY src/ ./src/


CMD ["uv", "run", "python", "-m", "src.main"]
